language: minimal

dist: bionic

services:
- docker

# docker >= 19.03 is required for docker buildx, so it is upgraded
before_install:
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y

script:
- make test

deploy:
- provider: script
  script: make release
  on:
    repo: aler9/rtsp-simple-server
    tags: true

- provider: releases
  api_key: $GITHUB_API_KEY
  skip_cleanup: true
  file_glob: true
  file: release/*
  on:
    repo: aler9/rtsp-simple-server
    tags: true

- provider: script
  script: docker login -u aler9 -p $DOCKER_PASSWORD && make dockerhub
  on:
    repo: aler9/rtsp-simple-server
    tags: true
