namespace Mediar.Codecs.Vorbis.Decoder;

/// <summary>
/// Vorbis codebook (Vorbis I spec §3.2). A codebook maps Huffman codewords to
/// either scalar entries (for plain VQ) or vectors of length
/// <see cref="Dimensions"/> (for vector quantization). Codewords are packed
/// MSB-first inside Vorbis bit streams even though the bit stream as a whole
/// is LSB-first — see <see cref="DecodeScalar"/> for the unpacking rule.
/// </summary>
internal sealed class VorbisCodebook
{
    /// <summary>Number of vector entries.</summary>
    public int Entries { get; private init; }

    /// <summary>Dimension of each entry's value vector.</summary>
    public int Dimensions { get; private init; }

    /// <summary>Per-entry codeword length in bits (0 means "unused entry").</summary>
    public byte[] CodewordLengths { get; private init; } = [];

    /// <summary>VQ lookup type (0 = none, 1 = lattice, 2 = explicit).</summary>
    public int LookupType { get; private init; }

    /// <summary>Per-entry interpreted value vector (length = Entries * Dimensions). Null when <see cref="LookupType"/> == 0.</summary>
    public float[]? ValueVectors { get; private init; }

    // Decoding tables. We build a flat Huffman tree for fast O(codeLength) decoding.
    private int[] _huffNodeLeft = [];   // child index for bit '0'
    private int[] _huffNodeRight = [];  // child index for bit '1'
    private int[] _huffNodeEntry = [];  // leaf entry, or -1 for non-leaf

    /// <summary>
    /// Parse one codebook from the Vorbis setup header at the current
    /// reader position. Throws <see cref="InvalidDataException"/> if the
    /// codebook is malformed.
    /// </summary>
    public static VorbisCodebook Parse(ref VorbisBitReader r)
    {
        // Sync pattern: 0x564342 (24-bit, LSB-first → bytes 0x42 0x43 0x56).
        uint sync = r.ReadBits(24);
        if (sync != 0x564342u)
        {
            throw new InvalidDataException($"Bad codebook sync pattern 0x{sync:X6}.");
        }

        int dims = (int)r.ReadBits(16);
        int entries = (int)r.ReadBits(24);

        var lengths = new byte[entries];
        bool ordered = r.ReadBit();
        if (!ordered)
        {
            bool sparse = r.ReadBit();
            for (int i = 0; i < entries; i++)
            {
                if (sparse)
                {
                    bool used = r.ReadBit();
                    lengths[i] = used ? (byte)(r.ReadBits(5) + 1) : (byte)0;
                }
                else
                {
                    lengths[i] = (byte)(r.ReadBits(5) + 1);
                }
            }
        }
        else
        {
            int currentLen = (int)(r.ReadBits(5) + 1);
            int current = 0;
            while (current < entries)
            {
                int bitsNeeded = VorbisBitReader.Ilog(entries - current);
                int number = (int)r.ReadBits(bitsNeeded);
                if (current + number > entries)
                    throw new InvalidDataException("Codebook ordered length run overflow.");
                for (int i = current; i < current + number; i++) lengths[i] = (byte)currentLen;
                current += number;
                currentLen++;
                if (currentLen > 32 && current < entries)
                    throw new InvalidDataException("Codebook ordered length exceeded 32 bits.");
            }
        }

        int lookupType = (int)r.ReadBits(4);
        float[]? values = null;
        if (lookupType == 1 || lookupType == 2)
        {
            uint minVal = r.ReadBits(32);
            uint delVal = r.ReadBits(32);
            int valueBits = (int)(r.ReadBits(4) + 1);
            bool sequenceP = r.ReadBit();
            float min = VorbisBitReader.Float32Unpack(minVal);
            float del = VorbisBitReader.Float32Unpack(delVal);

            int lookupValues = lookupType == 1
                ? VorbisBitReader.Lookup1Values(entries, dims)
                : entries * dims;

            var multiplicands = new uint[lookupValues];
            for (int i = 0; i < lookupValues; i++)
            {
                multiplicands[i] = r.ReadBits(valueBits);
            }

            values = new float[(long)entries * dims];
            if (lookupType == 1)
            {
                // Lattice VQ: each entry's vector is generated by walking the
                // multiplicand cube in mixed-radix order.
                for (int entry = 0; entry < entries; entry++)
                {
                    double last = 0;
                    int divisor = 1;
                    for (int d = 0; d < dims; d++)
                    {
                        int offset = (entry / divisor) % lookupValues;
                        double v = multiplicands[offset] * del + min + last;
                        values[(long)entry * dims + d] = (float)v;
                        if (sequenceP) last = v;
                        divisor *= lookupValues;
                    }
                }
            }
            else
            {
                // lookupType == 2: explicit list, dims per entry.
                for (int entry = 0; entry < entries; entry++)
                {
                    double last = 0;
                    for (int d = 0; d < dims; d++)
                    {
                        int idx = entry * dims + d;
                        double v = multiplicands[idx] * del + min + last;
                        values[(long)entry * dims + d] = (float)v;
                        if (sequenceP) last = v;
                    }
                }
            }
        }
        else if (lookupType != 0)
        {
            throw new InvalidDataException($"Unsupported codebook lookup type {lookupType}.");
        }

        var cb = new VorbisCodebook
        {
            Entries = entries,
            Dimensions = dims,
            CodewordLengths = lengths,
            LookupType = lookupType,
            ValueVectors = values,
        };
        cb.BuildHuffmanTree();
        return cb;
    }

    private void BuildHuffmanTree()
    {
        int cap = Math.Max(2, Entries * 2);
        _huffNodeLeft = new int[cap];
        _huffNodeRight = new int[cap];
        _huffNodeEntry = new int[cap];
        for (int i = 0; i < cap; i++)
        {
            _huffNodeLeft[i] = -1;
            _huffNodeRight[i] = -1;
            _huffNodeEntry[i] = -1;
        }
        int nodeCount = 1; // index 0 = root

        // Vorbis canonical Huffman assignment, as documented in the spec
        // §3.2.1 and the public-domain libvorbis _make_words reference.
        // `marker[L]` tracks the next available codeword of length L.
        Span<uint> marker = stackalloc uint[33];
        marker.Clear();

        int usedCount = 0;
        for (int i = 0; i < Entries; i++)
        {
            int len = CodewordLengths[i];
            if (len <= 0) continue;
            if (len > 32) throw new InvalidDataException("Codeword length exceeds 32 bits.");
            usedCount++;

            uint entry = marker[len];
            if (len < 32 && (entry >> len) != 0)
            {
                throw new InvalidDataException("Codebook is over-specified.");
            }

            // Place this codeword in the tree (MSB-first bit walk).
            int cur = 0;
            for (int b = len - 1; b >= 0; b--)
            {
                int bit = (int)((entry >> b) & 1u);
                ref int child = ref (bit == 0 ? ref _huffNodeLeft[cur] : ref _huffNodeRight[cur]);
                if (child < 0)
                {
                    if (nodeCount >= _huffNodeEntry.Length) GrowNodes();
                    child = nodeCount++;
                }
                cur = child;
            }
            if (_huffNodeEntry[cur] >= 0 || _huffNodeLeft[cur] >= 0 || _huffNodeRight[cur] >= 0)
            {
                throw new InvalidDataException("Codebook is not prefix-free.");
            }
            _huffNodeEntry[cur] = i;

            // Advance marker[len]; if the bit just consumed was already a
            // continuation slot for a shorter codeword, carry up.
            for (int j = len; j > 0; j--)
            {
                if ((marker[j] & 1) != 0)
                {
                    if (j == 1) marker[1]++;
                    else marker[j] = marker[j - 1] << 1;
                    break;
                }
                marker[j]++;
            }

            // Prune children of any deeper level that just became the prefix
            // of the codeword we placed.
            for (int j = len + 1; j < 33; j++)
            {
                if ((marker[j] >> 1) == entry)
                {
                    entry = marker[j];
                    marker[j] = marker[j - 1] << 1;
                }
                else break;
            }
        }

        // Spec allows a degenerate single-entry codebook (length 1 with one
        // entry); decode from a codebook with zero used entries is undefined.
        _ = usedCount;
    }

    private void GrowNodes()
    {
        int newCap = _huffNodeEntry.Length * 2;
        Array.Resize(ref _huffNodeLeft, newCap);
        Array.Resize(ref _huffNodeRight, newCap);
        Array.Resize(ref _huffNodeEntry, newCap);
        for (int i = _huffNodeEntry.Length / 2; i < newCap; i++)
        {
            _huffNodeLeft[i] = -1;
            _huffNodeRight[i] = -1;
            _huffNodeEntry[i] = -1;
        }
    }

    /// <summary>
    /// Decode one codebook entry from the bit stream. Each consumed bit walks
    /// the Huffman tree from root toward a leaf. Codewords are read bit-by-bit
    /// in the order produced by the encoder — for Vorbis that's MSB-first
    /// within the codeword, which matches the order our tree-build emitted.
    /// </summary>
    public int DecodeScalar(ref VorbisBitReader r)
    {
        int cur = 0;
        while (true)
        {
            // Within a Huffman codeword, bits are consumed in encoder order;
            // each bit chooses left (0) or right (1) child.
            uint bit = r.ReadBits(1);
            if (r.EndOfPacket) return -1;
            cur = bit == 0 ? _huffNodeLeft[cur] : _huffNodeRight[cur];
            if (cur < 0) throw new InvalidDataException("Codebook decode walked off the tree.");
            int leaf = _huffNodeEntry[cur];
            if (leaf >= 0) return leaf;
        }
    }

    /// <summary>
    /// Decode one VQ vector from the bit stream and write it into
    /// <paramref name="destination"/> (length must be at least <see cref="Dimensions"/>).
    /// Returns the entry index, or -1 on EOP.
    /// </summary>
    public int DecodeVector(ref VorbisBitReader r, scoped Span<float> destination)
    {
        if (LookupType == 0 || ValueVectors is null)
            throw new InvalidOperationException("Codebook has no value vectors.");
        int entry = DecodeScalar(ref r);
        if (entry < 0) return -1;
        ValueVectors.AsSpan((int)((long)entry * Dimensions), Dimensions).CopyTo(destination);
        return entry;
    }
}
