name: Bug report
description: Report a bug

body:
  - type: markdown
    attributes:
      value: |
        To increase the chance of your bug getting fixed, open an issue FOR EACH bug. Do not report multiple problems in a single issue, otherwise they'll probably never get all fixed.

  - type: input
    id: version
    attributes:
      label: Which version are you using?
      description: MediaMTX version or commit
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Which operating system are you using?
      multiple: true
      options:
        - Linux amd64 standard
        - Linux amd64 Docker
        - Linux arm64 standard
        - Linux arm64 Docker
        - Linux arm7 standard
        - Linux arm7 Docker
        - Linux arm6 standard
        - Linux arm6 Docker
        - Windows amd64 standard
        - Windows amd64 Docker (WSL backend)
        - macOS amd64 standard
        - macOS amd64 Docker
        - Other (please describe)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
    validations:
      required: true

  - type: textarea
    id: replica
    attributes:
      label: Describe how to replicate the issue
      description: |
        The maintainers must be able to REPLICATE your issue to solve it - therefore, describe in a very detailed way how to replicate it.
      value: |
        1. start the MediaMTX
        2. publish with ...
        3. read with ...
    validations:
      required: true

  - type: textarea
    id: conf
    attributes:
      label: MediaMTX configuration
      description: |
        MediaMTX configuration is often required to replicate the issue.
      placeholder: Paste the configuration file here
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: MediaMTX logs
      description: |
        MediaMTX logs are often useful to identify the issue. If you think this is the case, set 'logLevel' to 'debug' and attach logs.
      placeholder: Paste or drag the log file here

  - type: textarea
    id: network
    attributes:
      label: Packet dump
      description: |
        If the bug arises when using MediaMTX with external hardware or software, the most helpful information you can provide is a packet dump, that can be generated in this way:

        1. In mediamtx.yml, set 'dumpPackets' to 'true'
        2. Start the server and replicate the issue
        3. Stop the server, find the generated .pcapng files in the current directory
        4. Attach the pcapng files by dragging them here

      placeholder: Attach the pcapng files by dragging them here
