#!/bin/sh

# Mediamtx FreeBSD Service Script

# PROVIDE: mediamtx
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=mediamtx
user=www
rcvar=mediamtx_enable

: ${mediamtx_enable:="NO"}

pidfile=/var/run/${name}.pid
command=/usr/sbin/daemon
command_args="-r -u ${user} -P ${pidfile} /usr/local/bin/${name}"

load_rc_config $name
run_rc_command "$1"
