package rpicamera

type params struct {
	LogLevel          string
	CameraID          uint
	Width             uint
	Height            uint
	HFlip             bool
	VFlip             bool
	Brightness        float64
	Contrast          float64
	Saturation        float64
	Sharpness         float64
	Exposure          string
	AWB               string
	AWBGainRed        float64
	AWBGainBlue       float64
	Denoise           string
	Shutter           uint
	Metering          string
	Gain              float64
	EV                float64
	ROI               string
	HDR               bool
	TuningFile        string
	Mode              string
	FPS               float64
	AfMode            string
	AfRange           string
	AfSpeed           string
	LensPosition      float64
	AfWindow          string
	FlickerPeriod     uint
	TextOverlayEnable bool
	TextOverlay       string
	Codec             string
	IDRPeriod         uint
	Bitrate           uint
	Profile           string
	Level             string
}
